### ISSUE TITLE
binary_key pas défini

### ISSUE THREAD

**Issue by davidpichardie** [pmhoudry/python-Paybox#10]
https://github.com/pmhoudry/pythonPaybox/blob/fd1ecf1b664e25532812b36aeca797330c988a2e/Paybox.py#L94

Je pense qu'il manque le lien entre binary_key et self.SECRET
```
binary_key = binascii.unhexlify(self.SECRET)
```

**Comment by pmhoudry** [comment]
En effet, merci. C'est corrigé.
