### ISSUE TITLE
Python3 and SHA.new

### ISSUE THREAD

**Issue by davidpichardie** [pmhoudry/python-Paybox#11]
https://github.com/pmhoudry/pythonPaybox/blob/1844e8a1b82bad6539d924c2472572b26560873b/Paybox.py#L198

With Python3, the SHA.new function can not take a direct str as argument.
https://stackoverflow.com/questions/55672121/updating-to-python3-from-2-typeerror-can-only-concatenate-str-not-bytes-to

Patch: h = SHA.new(message_without_sign.encode('utf-8'))

**Comment by pmhoudry** [comment]
The script was not python3 compatible although I use in prod a modified version of it which is. I just comitted a new version which drops support for python2, and works on python3. 

Thanks for the precision of your issue !
