### ISSUE TITLE
Compatibility with django up to 1.10

### ISSUE THREAD

**Issue by pepourquier** [pmhoudry/python-Paybox#6]
I,
you could add a file apps.py in your project in order to use it with django up to 1.10

Here my file apps.py
```
from django.apps import AppConfig

class PythonPayboxConfig(AppConfig):
    name = 'pythonPaybox'
```

**Comment by pmhoudry** [comment]
Thanks for the nice and useful suggestion. Could you send a PR ?

**Comment by pepourquier** [comment]
Hi, I just did it.
