### ISSUE TITLE
Problème d'encodage lors de la création du formulaire

### ISSUE THREAD

**Issue by pepourquier** [pmhoudry/python-Paybox#8]
Le site sur lequel je travaille a levé l'exception suivante.

`Unicode-objects must be encoded before hashing`

Je n'ai eu aucun soucis sur un précédent site. Seule différence : l'utilisation de python3.5 sur le dernier.
Dans ma vue, l'erreur se produit sur cette ligne :
        `form_values = transaction.post_to_paybox()`
Et renvoie sur les fichiers suivants : 
```
/pythonPaybox/Paybox.py in post_to_paybox
        signature = hmac.new(binary_key, tosign, hashlib.sha512).hexdigest().upper()
▶ Local vars
/lib/python3.5/hmac.py in new
        signature = hmac.new(binary_key, tosign, hashlib.sha512).hexdigest().upper()
▶ Local vars
/lib/python3.5/hmac.py in __init__
        return HMAC(key, msg, digestmod)
▶ Local vars
/lib/python3.5/hmac.py in update
        self.inner.update(msg)
```
     
Python3.5 pourrait-il en être la cause ?

**Comment by pmhoudry** [comment]
En effet, je n'ai pas testé avec python3+. La solution a votre souci semble être ici : https://stackoverflow.com/questions/13265439/python-3-3-unicode-objects-must-be-encoded-before-hashing

Il semble donc qu'il faille encoder `binary_key` et `tosign` en utf-8 avant de générer la signature.

Pourriez vous tester cette solution et me faire retour de son bon fonctionnement ? Je pourrai ensuite l'intégrer.

**Comment by pepourquier** [comment]
Le test est concluant. 
J'ai fait un pull request #9
